FROM postgres:9.6
MAINTAINER Open Knowledge

# Customize default user/pass/db
ENV POSTGRES_USER ckan
ENV POSTGRES_PASSWORD ckan$$
# Production password generated with Dashlane => CsEKM2$M0+2rg$
ENV POSTGRES_DB ckan
